# for a description of available keys, see https://github.com/typst/packages/?tab=readme-ov-file#package-format

[package]
name = "my-resume"
version = "0.1.0"
entrypoint = "src/lib.typ"
authors = ["Dan Li"]
license = "Unlicense"
description = "A simple, standard resume, designed to work well with ATS."
repository = "https://github.com/danli-ds/basic-typst-resume-template"
keywords = ["cv", "resume", "ATS"]
categories = ["cv"]
exclude = [
	".github",
	"docs",
	"scripts",
	"tests",
	".typstignore",
	"Justfile",
]

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"
